name: Java CI with Maven

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
        cache-dependency-path: 'sub-project/pom.xml' # optional
    - name: Build with Maven
      run: mvn -B package --file pom.xml
